// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7tHqFP_8FqNO1o3slA1ch01Uq3bxPSDI',
    appId: '1:654117270418:web:a9486841ad4fcfb40ac74b',
    messagingSenderId: '654117270418',
    projectId: 'scholar-chat-1cc87',
    authDomain: 'scholar-chat-1cc87.firebaseapp.com',
    databaseURL: 'https://scholar-chat-1cc87-default-rtdb.firebaseio.com',
    storageBucket: 'scholar-chat-1cc87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD83MmT_FAKIiq0l3jmgA5VOI0PGdXTcyw',
    appId: '1:654117270418:android:336218e5540abed20ac74b',
    messagingSenderId: '654117270418',
    projectId: 'scholar-chat-1cc87',
    databaseURL: 'https://scholar-chat-1cc87-default-rtdb.firebaseio.com',
    storageBucket: 'scholar-chat-1cc87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJz0Y_uE3SwJBSowOuMNAnF9IDffnv0EE',
    appId: '1:654117270418:ios:9163b07365d0202a0ac74b',
    messagingSenderId: '654117270418',
    projectId: 'scholar-chat-1cc87',
    databaseURL: 'https://scholar-chat-1cc87-default-rtdb.firebaseio.com',
    storageBucket: 'scholar-chat-1cc87.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
